x-common-variables: &common-variables
  # From Coolify
  SOURCE_COMMIT: '${SOURCE_COMMIT}'

  # PHP
  APP_NAME: '${APP_NAME}'
  APP_KEY: '${APP_KEY}'
  APP_ENV: 'production'
  APP_DEBUG: '${APP_DEBUG:-false}'
  APP_URL: '${APP_URL}'

  LOG_LEVEL: '${LOG_LEVEL:-debug}'
  LOG_CHANNEL: 'stack'
  LOG_STACK: 'single,stderr'

  DB_CONNECTION: 'mysql'
  DB_HOST: 'mysql'
  DB_PORT: '3306'
  DB_DATABASE: '${DB_DATABASE:-mailcoach_db}'
  DB_USERNAME: '${DB_USERNAME:-mailcoach_user}'
  DB_PASSWORD: '${DB_PASSWORD}'

  CACHE_STORE: 'redis'
  QUEUE_CONNECTION: 'redis'
  SESSION_DRIVER: 'redis'

  REDIS_HOST: 'redis'

  # Node.js
  NODE_ENV: 'production'

services:

    laravel:
        build:
          dockerfile: Dockerfile
          context: .
          args:
            COMPOSER_AUTH: '${COMPOSER_AUTH}'
        environment:
          PHP_FPM_POOL_NAME: "my-app_php"

          <<: *common-variables
        volumes:
            - 'mailcoach-storage:/var/www/html/storage'
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_healthy


    laravel-horizon:
        build:
          dockerfile: Dockerfile
          context: .
          args:
            COMPOSER_AUTH: '${COMPOSER_AUTH}'
        command: ["php", "/var/www/html/artisan", "horizon"]
        environment:
          PHP_FPM_POOL_NAME: "my-app_horizon"

          <<: *common-variables
        volumes:
          - 'mailcoach-storage:/var/www/html/storage'
        depends_on:
            - laravel


    mysql:
        image: 'mysql:8'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mailcoach-db:/var/lib/mysql'
        healthcheck:
          # https://stackoverflow.com/a/54854239
          test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
          interval: 5s


    redis:
        image: 'redis:alpine'
        healthcheck:
          # https://stackoverflow.com/a/70706628
          test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
